version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      tooling:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "typescript*"
          - "jest*"
          - "ts-jest"
          - "@types/jest"
          - "esbuild"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
