import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "node:module";
import path from "node:path";
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	rmSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { brotliCompressSync, constants } from "node:zlib";
import { loadEnvLocal } from "./scripts/load-env-local.mjs";

loadEnvLocal();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const analyze = process.argv.includes("--analyze");

const OBSIDIAN_VAULT = process.env.OBSIDIAN_VAULT;
const OBSIDIAN_PLUGIN_PATH = OBSIDIAN_VAULT && existsSync(OBSIDIAN_VAULT)
	? path.join(OBSIDIAN_VAULT, ".obsidian", "plugins", "marp-extended")
	: null;
const OBSIDIAN_PLUGIN_DEPLOY_FILES = new Set(["main.js", "manifest.json", "styles.css", "marp-engine.cjs"]);
const OBSIDIAN_PLUGIN_RUNTIME_FILES = new Set(["data.json"]);

function pruneStaleObsidianPluginArtifacts(pluginPath) {
	const keep = new Set([...OBSIDIAN_PLUGIN_DEPLOY_FILES, ...OBSIDIAN_PLUGIN_RUNTIME_FILES]);
	for (const name of readdirSync(pluginPath)) {
		if (keep.has(name)) {
			continue;
		}
		rmSync(path.join(pluginPath, name), { recursive: true, force: true });
		console.log(`Removed stale Obsidian plugin artifact: ${name}`);
	}
}

const copyToObsidian = {
	name: "copy-to-obsidian",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0 || !OBSIDIAN_PLUGIN_PATH) {
				return;
			}

			if (!existsSync(OBSIDIAN_PLUGIN_PATH)) {
				mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true });
			}

			pruneStaleObsidianPluginArtifacts(OBSIDIAN_PLUGIN_PATH);

			for (const file of OBSIDIAN_PLUGIN_DEPLOY_FILES) {
				if (existsSync(file)) {
					copyFileSync(file, path.join(OBSIDIAN_PLUGIN_PATH, file));
					console.log(`Copied ${file} to Obsidian plugin folder`);
				}
			}
		});
	},
};

const sourceMapQuickSortShim = {
	name: "source-map-js-quick-sort-shim",
	setup(build) {
		const shimPath = path.resolve("src/shims/source-map-js-quick-sort.js");
		build.onResolve({ filter: /source-map-js\/lib\/quick-sort$/ }, () => ({ path: shimPath }));
		build.onResolve({ filter: /^\.\/quick-sort$/ }, (args) => (
			args.importer.includes("source-map-js/lib/")
				? { path: shimPath }
				: null
		));
	},
};

/**
 * Replace Marp Core's full Shiki language registry (#marp-shiki) with a curated
 * subset suitable for slide decks. Cuts multi‑MB of unused grammar packs.
 */
const marpShikiLangSubsetShim = {
	name: "marp-shiki-lang-subset",
	setup(build) {
		const shimPath = path.resolve("src/shims/marp-shiki.cjs");
		build.onResolve({ filter: /^#marp-shiki$/ }, () => ({ path: shimPath }));
		build.onResolve({ filter: /@marp-team\/marp-core\/lib\/internals\/shiki(\.node)?(\.cjs|\.mjs)?$/ }, () => ({
			path: shimPath,
		}));
	},
};

const engineExternal = [
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
];

/**
 * Marp Core hard-requires three cold MathJax font extensions (bbm, bboldx,
 * dsfont). Stub them out: same export names, no glyph data. Niche macros
 * degrade to a console warning; mhchem stays a real dependency.
 */
const mathjaxColdFontExtensionStub = {
	name: "mathjax-cold-font-extension-stub",
	setup(build) {
		build.onResolve({ filter: /@mathjax\/mathjax-(?:bbm|bboldx|dsfont)-font-extension\/mjs\/svg\.js$/ }, () => ({
			path: path.resolve("src/shims/mathjax-cold-font-extensions.cjs"),
		}));
	},
};

function verifyStandaloneEngine() {
	const enginePath = path.resolve("marp-engine.cjs");
	const require = createRequire(import.meta.url);
	delete require.cache[enginePath];
	const engineModule = require(enginePath);
	const createEngine = engineModule.default ?? engineModule;
	const first = createEngine({ container: [], slideContainer: [] });
	const second = createEngine({ container: [], slideContainer: [] });
	const rendered = first.render([
		"<!-- presenter note -->",
		"# Runtime probe",
		"",
		"* fragment",
		"",
		"```ts",
		"const answer: number = 42",
		"```",
		"",
		"$E=mc^2$",
	].join("\n"));
	const checks = {
		factory: typeof createEngine === "function" && first !== second,
		comments: rendered.comments?.[0]?.[0] === "presenter note",
		fragments: rendered.html.includes('data-marpit-fragment="1"'),
		shiki: rendered.html.includes("shiki"),
		mathjax: /mjx|MathJax/i.test(rendered.html),
	};
	const failed = Object.entries(checks).filter(([, passed]) => !passed).map(([name]) => name);
	if (failed.length > 0) throw new Error(`Standalone engine smoke check failed: ${failed.join(", ")}`);
}

async function buildEngine() {
	const result = await esbuild.build({
		entryPoints: ["src/runtime/cliEngine.ts"],
		bundle: true,
		platform: "node",
		format: "cjs",
		target: "node20",
		minify: true,
		treeShaking: true,
		metafile: true,
		external: engineExternal,
		plugins: [sourceMapQuickSortShim, marpShikiLangSubsetShim, mathjaxColdFontExtensionStub],
		outfile: "marp-engine.cjs",
		logLevel: "info",
	});
	const leaked = Object.keys(result.metafile.inputs).find((input) => /(?:^|[/\\])obsidian(?:[/\\]|$)/i.test(input));
	if (leaked || /require\(["']obsidian["']\)/.test(readFileSync("marp-engine.cjs", "utf8"))) {
		throw new Error(`Standalone engine must not import or externalize Obsidian${leaked ? `: ${leaked}` : "."}`);
	}
	if (prod) verifyStandaloneEngine();
}

const engineBuildPlugin = {
	name: "build-standalone-marp-engine",
	setup(build) {
		build.onStart(buildEngine);
	},
};

const embeddedEnginePlugin = {
	name: "embedded-marp-engine",
	setup(build) {
		build.onResolve({ filter: /^marp-extended:embedded-engine$/ }, () => ({
			path: "embedded-engine",
			namespace: "marp-extended",
		}));
		build.onLoad({ filter: /.*/, namespace: "marp-extended" }, () => {
			const bytes = readFileSync("marp-engine.cjs");
			const compressed = brotliCompressSync(bytes, {
				params: {
					[constants.BROTLI_PARAM_QUALITY]: constants.BROTLI_MAX_QUALITY,
					[constants.BROTLI_PARAM_SIZE_HINT]: bytes.length,
				},
			});
			return {
				contents: `export const brotliBase64=${JSON.stringify(compressed.toString("base64"))};export const sha256=${JSON.stringify(createHash("sha256").update(bytes).digest("hex"))};`,
				loader: "js",
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [engineBuildPlugin, sourceMapQuickSortShim, marpShikiLangSubsetShim, mathjaxColdFontExtensionStub, embeddedEnginePlugin, copyToObsidian],
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"chromium-bidi/lib/cjs/bidiMapper/bidiMapper.js",
		"emitter",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",		
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	metafile: analyze,
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	const result = await context.rebuild();
	if (analyze && result.metafile) {
		await import("node:fs/promises").then(({ writeFile }) =>
			writeFile("metafile.json", JSON.stringify(result.metafile))
		);
		console.log("Wrote metafile.json — open at https://esbuild.github.io/analyze/");
	}
	await context.dispose();
} else {
	// Shared runtime edits are inputs to the main bundle. Its onStart hook rebuilds
	// the standalone artifact before refreshing the embedded payload.
	await context.watch();
}
