import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const analyze = process.argv.includes("--analyze");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"chromium-bidi/lib/cjs/bidiMapper/bidiMapper.js",
		"emitter",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",		
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	metafile: analyze,
	treeShaking: true,
	//outfile: "vault/.obsidian/plugins/marp-extended/main.js", //for local dev!!!
	outfile: "main.js",
});

if (prod) {
	const result = await context.rebuild();
	if (analyze && result.metafile) {
		await import("node:fs/promises").then(({ writeFile }) =>
			writeFile("metafile.json", JSON.stringify(result.metafile))
		);
		console.log("Wrote metafile.json — open at https://esbuild.github.io/analyze/");
	}
	process.exit(0);
} else {
	await context.watch();
}
