import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import path from "node:path";
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
} from "node:fs";

if (existsSync(".env.local")) {
	const envContent = readFileSync(".env.local", "utf-8");
	for (const line of envContent.split("\n")) {
		const match = line.match(/^([^=#]+)=["']?(.+?)["']?$/);
		if (match && !process.env[match[1]]) {
			process.env[match[1]] = match[2];
		}
	}
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const analyze = process.argv.includes("--analyze");

const OBSIDIAN_VAULT = process.env.OBSIDIAN_VAULT;
const OBSIDIAN_PLUGIN_PATH = OBSIDIAN_VAULT && existsSync(OBSIDIAN_VAULT)
	? path.join(OBSIDIAN_VAULT, ".obsidian", "plugins", "marp-extended")
	: null;
const OBSIDIAN_PLUGIN_DEPLOY_FILES = new Set(["main.js", "manifest.json", "styles.css"]);
const OBSIDIAN_PLUGIN_RUNTIME_FILES = new Set(["data.json", "lib3"]);

function pruneStaleObsidianPluginArtifacts(pluginPath) {
	const keep = new Set([...OBSIDIAN_PLUGIN_DEPLOY_FILES, ...OBSIDIAN_PLUGIN_RUNTIME_FILES]);
	for (const name of readdirSync(pluginPath)) {
		if (keep.has(name)) {
			continue;
		}
		rmSync(path.join(pluginPath, name), { recursive: true, force: true });
		console.log(`Removed stale Obsidian plugin artifact: ${name}`);
	}
}

const copyToObsidian = {
	name: "copy-to-obsidian",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0 || !OBSIDIAN_PLUGIN_PATH) {
				return;
			}

			if (!existsSync(OBSIDIAN_PLUGIN_PATH)) {
				mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true });
			}

			pruneStaleObsidianPluginArtifacts(OBSIDIAN_PLUGIN_PATH);

			for (const file of OBSIDIAN_PLUGIN_DEPLOY_FILES) {
				if (existsSync(file)) {
					copyFileSync(file, path.join(OBSIDIAN_PLUGIN_PATH, file));
					console.log(`Copied ${file} to Obsidian plugin folder`);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	plugins: [copyToObsidian],
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"chromium-bidi/lib/cjs/bidiMapper/bidiMapper.js",
		"emitter",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",		
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	metafile: analyze,
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	const result = await context.rebuild();
	if (analyze && result.metafile) {
		await import("node:fs/promises").then(({ writeFile }) =>
			writeFile("metafile.json", JSON.stringify(result.metafile))
		);
		console.log("Wrote metafile.json — open at https://esbuild.github.io/analyze/");
	}
	process.exit(0);
} else {
	await context.watch();
}
