#!/usr/bin/env python3
"""Refresh upstream reference snapshots for the obsidian-marp skill."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DocPage:
    title: str
    url: str
    output_path: str
    converter: str = "defuddle"


DOC_PAGES = [
    DocPage("Agent Skills specification", "https://agentskills.io/specification", "agent-skills/specification.md"),
    DocPage("Marp homepage", "https://marp.app/", "marp/home.md"),
    DocPage("Marpit Markdown", "https://raw.githubusercontent.com/marp-team/marpit/main/docs/markdown.md", "marpit/markdown.md", "curl"),
    DocPage("Marpit directives", "https://raw.githubusercontent.com/marp-team/marpit/main/docs/directives.md", "marpit/directives.md", "curl"),
    DocPage("Marpit image syntax", "https://raw.githubusercontent.com/marp-team/marpit/main/docs/image-syntax.md", "marpit/image-syntax.md", "curl"),
    DocPage("Marpit fragmented list", "https://raw.githubusercontent.com/marp-team/marpit/main/docs/fragmented-list.md", "marpit/fragmented-list.md", "curl"),
    DocPage("Marpit theme CSS", "https://raw.githubusercontent.com/marp-team/marpit/main/docs/theme-css.md", "marpit/theme-css.md", "curl"),
    DocPage("Marp Core README", "https://raw.githubusercontent.com/marp-team/marp-core/main/README.md", "marp-core/README.md", "curl"),
    DocPage("Marp CLI README", "https://raw.githubusercontent.com/marp-team/marp-cli/main/README.md", "marp-cli/README.md", "curl"),
    DocPage("Marp CLI bespoke transitions", "https://raw.githubusercontent.com/marp-team/marp-cli/main/docs/bespoke-transitions/README.md", "marp-cli/bespoke-transitions.md", "curl"),
]


def run(cmd: list[str], *, allow_failure: bool = False) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(cmd))
    result = subprocess.run(cmd, check=False, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if result.returncode != 0 and not allow_failure:
        print(result.stdout, file=sys.stderr)
        raise SystemExit(result.returncode)
    return result


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def skill_root() -> Path:
    return Path(__file__).resolve().parents[1]


def download_with_curl(url: str, output: Path) -> None:
    run(["curl", "-fsSL", "-o", str(output), url])


def download_with_defuddle(url: str, output: Path) -> None:
    if shutil.which("npx") is None:
        print("npx not found; falling back to raw curl. HTML may not be converted cleanly.", file=sys.stderr)
        download_with_curl(url, output)
        return

    result = run(
        [
            "npx",
            "--yes",
            "defuddle",
            "parse",
            url,
            "--markdown",
            "--output",
            str(output),
        ],
        allow_failure=True,
    )
    if result.returncode == 0:
        return

    print(result.stdout, file=sys.stderr)
    print("defuddle failed; falling back to raw curl. HTML may not be converted cleanly.", file=sys.stderr)
    download_with_curl(url, output)


def refresh_upstream(reference_dir: Path) -> None:
    upstream_dir = reference_dir / "upstream"
    if upstream_dir.exists():
        shutil.rmtree(upstream_dir)
    upstream_dir.mkdir(parents=True)

    for page in DOC_PAGES:
        output = upstream_dir / page.output_path
        output.parent.mkdir(parents=True, exist_ok=True)
        if page.converter == "curl":
            download_with_curl(page.url, output)
        else:
            download_with_defuddle(page.url, output)

    write_generated_index(reference_dir)


def write_generated_index(reference_dir: Path) -> None:
    lines = [
        "# Generated upstream reference index",
        "",
        "This file is generated by `../scripts/update-references.py`.",
        "",
        "| Source | URL | Local snapshot |",
        "| --- | --- | --- |",
    ]
    for page in DOC_PAGES:
        lines.append(f"| {page.title} | {page.url} | `upstream/{page.output_path}` |")
    lines.append("")
    (reference_dir / "UPSTREAM_INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-dir", type=Path, default=skill_root() / "references")
    args = parser.parse_args()

    root = repo_root()
    if Path.cwd().resolve() != root:
        print(f"Tip: run from repo root for reproducible paths: {root}", file=sys.stderr)

    args.reference_dir.mkdir(parents=True, exist_ok=True)
    refresh_upstream(args.reference_dir)
    print(f"Updated {args.reference_dir / 'upstream'}")


if __name__ == "__main__":
    main()
