import { WRAP_GROUP_ID_PREFIX } from './zigzag';

function parsePositiveNumber(value: string | null | undefined): number | null {
	if (!value) {
		return null;
	}
	const match = value.trim().match(/^([0-9]+(?:\.[0-9]+)?)/);
	if (!match) {
		return null;
	}
	const parsed = Number(match[1]);
	return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

/**
 * Read the width/height aspect ratio of an SVG string, preferring explicit
 * width/height attributes and falling back to the viewBox. Returns null when
 * the size cannot be determined.
 */
export function readSvgAspectRatio(svg: string): number | null {
	const root = svg.match(/<svg\b[^>]*>/i)?.[0];
	if (!root) {
		return null;
	}

	const width = parsePositiveNumber(root.match(/\bwidth\s*=\s*"([^"]*)"/i)?.[1]);
	const height = parsePositiveNumber(root.match(/\bheight\s*=\s*"([^"]*)"/i)?.[1]);
	if (width != null && height != null) {
		return width / height;
	}

	const viewBox = root.match(/\bviewBox\s*=\s*"([^"]*)"/i)?.[1];
	if (viewBox) {
		const parts = viewBox.trim().split(/[\s,]+/).map(Number);
		if (parts.length === 4 && parts[2] > 0 && parts[3] > 0) {
			return parts[2] / parts[3];
		}
	}

	return null;
}

const WRAP_GROUP_PATTERN = new RegExp(
	`<g class="subgraph" data-id="${WRAP_GROUP_ID_PREFIX}\\d+"[^>]*>[\\s\\S]*?</g>`,
	'g',
);

/**
 * Remove the generated wrap-row group chrome (background rect, header band,
 * label) from a rendered SVG. beautiful-mermaid renders nodes outside group
 * elements, so dropping the whole `<g class="subgraph">` block is safe for
 * the flat groups generated by buildZigzagSource.
 */
export function stripWrapGroupChrome(svg: string): string {
	return svg.replace(WRAP_GROUP_PATTERN, '');
}
